name: yamllint

on:
  pull_request:
    paths:
      - '.yamllint.yml'
      - 'config/locales/en.yml'
      - 'config/locales/js-en.yml'
      - 'modules/*/config/locales/en.yml'
      - 'modules/*/config/locales/js-en.yml'

jobs:
  rubocop:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Run Yamllint
        uses: reviewdog/action-yamllint@f01d8a48fd8d89f89895499fca2cff09f9e9e8c0
        with:
          github_token: ${{ secrets.github_token }}
          filter_mode: diff_context
          yamllint_flags: >
            .yamllint.yml
            config/locales/en.yml
            config/locales/js-en.yml
            modules/*/config/locales/en.yml
            modules/*/config/locales/js-en.yml
